### ISSUE TITLE
[Bug]: Elytra Slot with Cape Texture, No Trim on 3.0.0 & 3.1.1

### ISSUE THREAD

**Issue by ninjaeon** [Kikugie/elytra-trims#55]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

3.1.1

### Affected mods

- [X] Elytra Trims
- [ ] Extensions

### Bug description

I've reverted back to 2.1.2 so that I can see trims, but I still got cape texture issue on that version as well in the Elytra slot added by elytratrinket/elytraslot

elytratrims-fabric-3.1.1+1.20.1.jar = Cape texture on both Elytra slot and chest slot, No trim on both slots, dye appears on both slots

elytratrims-fabric-2.1.2+1.20.1.jar = Cape texture on Elytra slot, Elytra texture on chest slot, trim & dye appears on both slots

Client Log elytratrims-fabric-2.1.2+1.20.1.jar:
https://mclo.gs/wraTgYq

Client Log elytratrims-fabric-3.1.1+1.20.1.jar:
https://mclo.gs/H62KJPV

I also had the same issues as 3.1.1 on elytratrims-fabric-3.0.0+1.20.1.jar

Tried both elytra slot mods (separately, not at same time):
elytra_trinket-1.0.3.jar
elytraslot-fabric-6.3.0+1.20.1.jar

![image](https://github.com/kikugie/elytra-trims/assets/10052279/1026256a-879b-4100-8588-3952a1dcf393)
_3.1.1 in Elytra slot, Tide trim, black dye_

### Relevant logs

https://mclo.gs/H62KJPV

**Comment by kikugie** [comment]
I can't reproduce the issue with only Elytra Trims and Elytra Trinket/Elytra Slot. It works as it should:
- Elytra equipped in the cape slot shows trims, patterns and other overlays.
- Setting "Cape: None" in the mod config disables the player cape on the elytra, whenever in the chest or the cape trinket slot.

The game logs you provided contain plenty of mods, so I ask you to narrow it down, or otherwise provide a way to reproduce your environment (such as a modpack link or file)

**Comment by kikugie** [comment]
Due to inactivity I'll close this issue. If you need any help, reopen it or create a new one.
