### ISSUE TITLE
[Bug]: Crash when trying to customize elytras

### ISSUE THREAD

**Issue by Aceciito** [Kikugie/elytra-trims#70]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

6.4.0+1.20.1

### Affected mods

- [X] Elytra Trims
- [ ] Extensions

### Bug description

The mod wasn´t working so i thought it was because the model was set to 3D, when i tried to turn off the option it just crashes, in minecraft it says saving world before crashing.

### Steps to reproduce

Open minecraft
Go to mods
Go to the Elytra Trims mod and go to config
Crashes 

### Relevant logs

https://pastebin.com/5Qg8BPUU

**Comment by kikugie** [comment]
The config screen uses [YACL](https://modrinth.com/mod/yacl), which causes the crash in this case: `Caused by: java.lang.IncompatibleClassChangeError: class dev.isxander.yacl3.gui.OptionListWidget overrides final method net.minecraft.client.gui.components.AbstractSelectionList.m_6702_()Ljava/util/List;`  
I suggest reporting it on that issue tracker.  

@isXander lexforge issue, glhf

**Comment by Aceciito** [comment]
okay, thanks!

**Comment by isXander** [comment]
> The config screen uses [YACL](https://modrinth.com/mod/yacl), which causes the crash in this case: `Caused by: java.lang.IncompatibleClassChangeError: class dev.isxander.yacl3.gui.OptionListWidget overrides final method net.minecraft.client.gui.components.AbstractSelectionList.m_6702_()Ljava/util/List;` I suggest reporting it on that issue tracker.
> 
> @isXander lexforge issue, glhf

ffs lexforge i dont want to deal with that guy
