### ISSUE TITLE
Make it unto datapack like tool trims.

### ISSUE THREAD

**Issue by sadlyborger** [Kikugie/elytra-trims#73]
### Description

Would it be possible to make it unto datapack so that it can be use on server without everyone downloading like tool trims?
With use of Polymer.

**Comment by kikugie** [comment]
Making it a datapack on the server is not possible due to a couple things. One is that even in 1.21 recipes can only produce items with pre-set nbt tags. They can't append the data. And second is that banner patterns require a hardcoded recipe to copy the banner data to the elytra.

On the client you will need the mod in any case because elytras don't support these kind of features in vanilla. Even if you were to use entity model textures (you would need a mod for that anyway), but you would also not be able to reproduce what the mod does due to the large amount of combinations of banner patterns and trims.

In this case of tool trims, item textures have some overlay support, but you have significantly less variation.

As the last note, Elytra Trims is designed to not require both sides. You can install it on the server, but people will still be able to play without the mod on the client.

**Comment by sadlyborger** [comment]
Okay, thank you very much. No worries.
